language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gir1.2-gspell-1
  - pip install chardet flake8
script:
  - flake8 .
  - py.test aeidon
  - python setup.py install
  - python setup.py clean
